# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:

- task: CacheBeta@0
  inputs:
    key: Homew | $(Agent.OS) | 
    path: |
     /usr/local/Homebrew
     $HOME/Library/Caches/Homebrew 
  displayName: Cache homebrew

- script: |
    brew update
    brew tap henkrehorst/php
    brew install valet-php@7.2
    brew install composer
  displayName: 'Test install time valet-php@7.2'
