# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    brew update
    brew tap henkrehorst/php
    brew install valet-php@7.2
    brew install composer
    php -v
    composer global require weprovide/valet-plus
    export PATH="$PATH:$HOME/.composer/vendor/bin"
    valet install
    valet use 7.1
  displayName: 'Test install time valet-php@7.2'
